name: ci
run-name: ${{ github.actor }} is testing the website
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun run test

  build-image:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Go to directory
        run: cd /home/${{secrets.SSH_SERVER_USER}}/onetruejon/website/OneTrueJon
      - name: Log in to Docker
        run: echo ${{secrets.DOCKERHUB_ACCESS_TOKEN}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin	 
      - name: Build and Push
        run: |
          echo ${{secrets.SSH_SUDO_PASSWD}} | sudo -S docker build -t jmdowns00/website:latest .
  
  deploy:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{secrets.SSH_PRIVATE_KEY}}
          known_hosts: "Dummy value, will add this next step"
      - name: Adding Known Hosts
        run: ssh-keyscan -t ed25519 -p ${{secrets.SSH_SERVER_PORT}} -H ${{ secrets.SSH_SERVER_IP }} >> ~/.ssh/known_hosts
      - name: SSH into server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_SERVER_IP }}
          username: ${{ secrets.SSH_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_SERVER_PORT }}
          script: |
            cd /home/${{secrets.SSH_SERVER_USER}}/onetruejon/website
            OLDID=$(echo ${{secrets.SSH_SUDO_PASSWD}} | sudo -S docker ps | grep "jmdowns00/website:latest" | egrep -o "[0-9a-f]{12}")
            echo ${{secrets.SSH_SUDO_PASSWD}} | sudo -S docker-compose up -d --scale website=2 --no-recreate
            sleep 15
            echo ${{secrets.SSH_SUDO_PASSWD}} | sudo -S docker stop $OLDID
            echo ${{secrets.SSH_SUDO_PASSWD}} | sudo -S docker compose rm
            echo ${{secrets.SSH_SUDO_PASSWD}} | sudo -S docker-compose up -d --scale website=1 --no-recreate