name: test
run-name: ${{ github.actor }} is testing the website
on: [push]
jobs:
  check-jest-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install 
      - run: bun run test
